#!/usr/bin/env bash
# Copyright 2018 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -x

export SKIP_SNAPSHOT=yes
export LOG=file

# enable IPv6 if requested (requires container to be run privileged mode)
export IP_MODE=${IP_MODE:-ipv4}
if [[ "${IP_MODE}" == "ipv6" ]]; then
    sysctl -w net.ipv6.conf.all.disable_ipv6=0
fi

echo Bringing up a cluster and starting a bash shell
/usr/local/bin/runner.sh \
    /bin/bash -c '/root/kubeadm-dind-cluster/fixed/dind-cluster-stable.sh up && /bin/bash'
